### ISSUE TITLE
Add comments

### ISSUE THREAD

**Issue by romilrobtsenkov** [raikolepik/php-ruhmatoo-projekt#2]

**Comment by Raunts26** [comment]
Ei midagi erilist. Kommentaar lihtsalt teeb INSERT INTO tabelisse. Tasub vaadata, kas tabelis on olemas väli nagu checked või midagi taolist, et läheks enne kontrollimisele admin paneeli. Seejärel for loopiga asi välja tirida tabelist nii admin paneeli kui ka rate.phpsse.

**Comment by raikolepik** [comment]
valmis
