### ISSUE TITLE
Manager possibility (review comments)

### ISSUE THREAD

**Issue by romilrobtsenkov** [raikolepik/php-ruhmatoo-projekt#3]

**Comment by Raunts26** [comment]
Suhteliselt lebo asi saab olema, tehke Raikoga koos seda kommentaariumi värki ehk, vajadusel aitan. Tabelisse kuvab kuskil adminpaneelis kontrollimata kommentaarid. Nupu vajutamisel teeb UPDATE tabelis mingile väljale, kas siis 0 või 1(kontrollitud).

**Comment by ghost** [comment]
Vist nagu midagi teeb.
